import os
import numpy as np
import netCDF4 as nc
import matplotlib.pyplot as plt


# ============================================================
# FILE PATHS
# ============================================================

# Geolocation generated by the Geometry Module
GEODETIC_PATH = r"RUTA_AL_FICHERO_DE_GEOLOCALIZACION.nc"

# L1C output generated by your l1c.py
L1C_PATH = r"RUTA_AL_FICHERO_L1C_VNIR-0.nc"


# ============================================================
# AUXILIARY FUNCTION
# ============================================================

def get_variable(dataset, possible_names):
    """
    Search a NetCDF file for a variable using several possible names.
    """

    for name in possible_names:
        if name in dataset.variables:
            return np.array(dataset.variables[name][:])

    raise KeyError(
        "Variable not found. Available variables: "
        + str(list(dataset.variables.keys()))
    )


# ============================================================
# MAIN
# ============================================================

def main():

    # --------------------------------------------------------
    # 1. READ L1B GEOLOCATION
    # --------------------------------------------------------

    ds_geo = nc.Dataset(GEODETIC_PATH, "r")

    lat_l1b = get_variable(
        ds_geo,
        ["lat", "latitude", "Latitude"]
    )

    lon_l1b = get_variable(
        ds_geo,
        ["lon", "longitude", "Longitude"]
    )

    ds_geo.close()


    # --------------------------------------------------------
    # 2. READ L1C GEOLOCATION
    # --------------------------------------------------------

    ds_l1c = nc.Dataset(L1C_PATH, "r")

    lat_l1c = get_variable(
        ds_l1c,
        ["lat", "latitude", "Latitude"]
    )

    lon_l1c = get_variable(
        ds_l1c,
        ["lon", "longitude", "Longitude"]
    )

    ds_l1c.close()


    # --------------------------------------------------------
    # 3. INFORMATION
    # --------------------------------------------------------

    print("L1B latitude shape :", lat_l1b.shape)
    print("L1B longitude shape:", lon_l1b.shape)

    print("L1C latitude shape :", lat_l1c.shape)
    print("L1C longitude shape:", lon_l1c.shape)


    # --------------------------------------------------------
    # 4. PLOT L1B FOOTPRINT
    # --------------------------------------------------------

    plt.figure(figsize=(12, 6))

    # Upper border
    plt.plot(
        lon_l1b[0, :],
        lat_l1b[0, :],
        "k-",
        linewidth=1.5,
        label="L1B"
    )

    # Lower border
    plt.plot(
        lon_l1b[-1, :],
        lat_l1b[-1, :],
        "k-",
        linewidth=1.5
    )

    # Left border
    plt.plot(
        lon_l1b[:, 0],
        lat_l1b[:, 0],
        "k-",
        linewidth=1.5
    )

    # Right border
    plt.plot(
        lon_l1b[:, -1],
        lat_l1b[:, -1],
        "k-",
        linewidth=1.5
    )


    # --------------------------------------------------------
    # 5. PLOT L1C MGRS GRID
    # --------------------------------------------------------

    plt.scatter(
        lon_l1c.flatten(),
        lat_l1c.flatten(),
        s=4,
        c="red",
        label="L1C MGRS"
    )


    # --------------------------------------------------------
    # 6. FIGURE SETTINGS
    # --------------------------------------------------------

    plt.xlabel("Longitude [deg]")
    plt.ylabel("Latitude [deg]")

    plt.title("Projection on ground")

    plt.grid(True)
    plt.legend()

    plt.tight_layout()


    # --------------------------------------------------------
    # 7. SAVE FIGURE IN TEST DIRECTORY
    # --------------------------------------------------------

    test_directory = os.path.dirname(os.path.abspath(__file__))

    output_file = os.path.join(
        test_directory,
        "L1B_vs_L1C_grid.png"
    )

    plt.savefig(
        output_file,
        dpi=300
    )

    print("Figure saved in:")
    print(output_file)


    # Show figure
    plt.show()


if __name__ == "__main__":
    main()